INSERT INTO locations (city, country, region, country_code) VALUES
-- Major U.S. Cities
('New York', 'United States', 'New York', 'USA'),
('Los Angeles', 'United States', 'California', 'USA'),
('Chicago', 'United States', 'Illinois', 'USA'),
('Houston', 'United States', 'Texas', 'USA'),
('San Francisco', 'United States', 'California', 'USA'),
('Miami', 'United States', 'Florida', 'USA'),
('Boston', 'United States', 'Massachusetts', 'USA'),
('Seattle', 'United States', 'Washington', 'USA'),
('Dallas', 'United States', 'Texas', 'USA'),
('Washington', 'United States', 'D.C.', 'USA'),

-- Major Canadian Cities
('Toronto', 'Canada', 'Ontario', 'CAN'),
('Vancouver', 'Canada', 'British Columbia', 'CAN'),
('Montreal', 'Canada', 'Quebec', 'CAN'),
('Calgary', 'Canada', 'Alberta', 'CAN'),
('Ottawa', 'Canada', 'Ontario', 'CAN'),
('Edmonton', 'Canada', 'Alberta', 'CAN'),
('Quebec City', 'Canada', 'Quebec', 'CAN'),
('Winnipeg', 'Canada', 'Manitoba', 'CAN'),
('Halifax', 'Canada', 'Nova Scotia', 'CAN'),
('Victoria', 'Canada', 'British Columbia', 'CAN'),

-- Major European Cities (Western, Central, and Eastern Europe)
('London', 'United Kingdom', NULL, 'GBR'),
('Manchester', 'United Kingdom', NULL, 'GBR'),
('Paris', 'France', NULL, 'FRA'),
('Berlin', 'Germany', NULL, 'DEU'),
('Hamburg', 'Germany', NULL, 'DEU'),
('Munich', 'Germany', NULL, 'DEU'),
('Madrid', 'Spain', NULL, 'ESP'),
('Barcelona', 'Spain', NULL, 'ESP'),
('Rome', 'Italy', NULL, 'ITA'),
('Milan', 'Italy', NULL, 'ITA'),
('Amsterdam', 'Netherlands', NULL, 'NLD'),
('Stockholm', 'Sweden', NULL, 'SWE'),
('Zurich', 'Switzerland', NULL, 'CHE'),
('Vienna', 'Austria', NULL, 'AUT'),
('Copenhagen', 'Denmark', NULL, 'DNK'),
('Oslo', 'Norway', NULL, 'NOR'),
('Brussels', 'Belgium', NULL, 'BEL'),
('Lisbon', 'Portugal', NULL, 'PRT'),
('Dublin', 'Ireland', NULL, 'IRL'),
('Helsinki', 'Finland', NULL, 'FIN'),
('Warsaw', 'Poland', NULL, 'POL'),
('Prague', 'Czech Republic', NULL, 'CZE'),
('Budapest', 'Hungary', NULL, 'HUN'),
('Bucharest', 'Romania', NULL, 'ROU'),
('Sofia', 'Bulgaria', NULL, 'BGR'),
('Belgrade', 'Serbia', NULL, 'SRB'),

-- Major Israeli Cities
('Tel Aviv', 'Israel', NULL, 'ISR'),
('Jerusalem', 'Israel', NULL, 'ISR'),
('Haifa', 'Israel', NULL, 'ISR'),
('Beersheba', 'Israel', NULL, 'ISR'),
('Eilat', 'Israel', NULL, 'ISR'),

-- Major Middle Eastern Cities
('Dubai', 'United Arab Emirates', NULL, 'ARE'),
('Abu Dhabi', 'United Arab Emirates', NULL, 'ARE'),
('Riyadh', 'Saudi Arabia', NULL, 'SAU'),
('Jeddah', 'Saudi Arabia', NULL, 'SAU'),
('Doha', 'Qatar', NULL, 'QAT'),
('Manama', 'Bahrain', NULL, 'BHR'),
('Kuwait City', 'Kuwait', NULL, 'KWT'),
('Muscat', 'Oman', NULL, 'OMN'),
('Amman', 'Jordan', NULL, 'JOR'),
('Beirut', 'Lebanon', NULL, 'LBN'),

-- Major Asian Cities
('Tokyo', 'Japan', NULL, 'JPN'),
('Osaka', 'Japan', NULL, 'JPN'),
('Seoul', 'South Korea', NULL, 'KOR'),
('Busan', 'South Korea', NULL, 'KOR'),
('Shanghai', 'China', NULL, 'CHN'),
('Beijing', 'China', NULL, 'CHN'),
('Singapore', 'Singapore', NULL, 'SGP'),
('Bangkok', 'Thailand', NULL, 'THA'),
('Jakarta', 'Indonesia', NULL, 'IDN'),
('Manila', 'Philippines', NULL, 'PHL'),
('Cebu City', 'Philippines', NULL, 'PHL'),
('Ho Chi Minh City', 'Vietnam', NULL, 'VNM'),
('Hanoi', 'Vietnam', NULL, 'VNM'),
('Kuala Lumpur', 'Malaysia', NULL, 'MYS'),
('Mumbai', 'India', NULL, 'IND'),
('New Delhi', 'India', NULL, 'IND'),

-- Major Australian Cities
('Sydney', 'Australia', NULL, 'AUS'),
('Melbourne', 'Australia', NULL, 'AUS'),
('Brisbane', 'Australia', NULL, 'AUS'),
('Perth', 'Australia', NULL, 'AUS'),
('Adelaide', 'Australia', NULL, 'AUS'),
('Canberra', 'Australia', NULL, 'AUS');
