INSERT INTO user_profiles 
  (oauth_provider, oauth_provider_id, email, full_name, profile_picture, social_profile_url, user_type)
VALUES
  ('LinkedIn', 'LinkedIn_1', 'user1@example.com', 'User 1 Name', 'https://example.com/profiles/user1.jpg', 'https://social.example.com/user1', 'talent'),
  ('Google',    'Google_2',    'user2@example.com', 'User 2 Name', 'https://example.com/profiles/user2.jpg', 'https://social.example.com/user2', 'talent_recruiter'),
  ('X',         'X_3',         'user3@example.com', 'User 3 Name', 'https://example.com/profiles/user3.jpg', 'https://social.example.com/user3', 'talent'),
  ('Instagram', 'Instagram_4', 'user4@example.com', 'User 4 Name', 'https://example.com/profiles/user4.jpg', 'https://social.example.com/user4', 'talent_recruiter'),
  ('LinkedIn',  'LinkedIn_5',  'user5@example.com', 'User 5 Name', 'https://example.com/profiles/user5.jpg', 'https://social.example.com/user5', 'talent'),
  ('Google',    'Google_6',    'user6@example.com', 'User 6 Name', 'https://example.com/profiles/user6.jpg', 'https://social.example.com/user6', 'talent_recruiter'),
  ('X',         'X_7',         'user7@example.com', 'User 7 Name', 'https://example.com/profiles/user7.jpg', 'https://social.example.com/user7', 'talent'),
  ('Instagram', 'Instagram_8', 'user8@example.com', 'User 8 Name', 'https://example.com/profiles/user8.jpg', 'https://social.example.com/user8', 'talent_recruiter'),
  ('LinkedIn',  'LinkedIn_9',  'user9@example.com', 'User 9 Name', 'https://example.com/profiles/user9.jpg', 'https://social.example.com/user9', 'talent'),
  ('Google',    'Google_10',   'user10@example.com','User 10 Name','https://example.com/profiles/user10.jpg','https://social.example.com/user10','talent_recruiter'),
  ('X',         'X_11',        'user11@example.com','User 11 Name','https://example.com/profiles/user11.jpg','https://social.example.com/user11','talent'),
  ('Instagram', 'Instagram_12','user12@example.com','User 12 Name','https://example.com/profiles/user12.jpg','https://social.example.com/user12','talent_recruiter'),
  ('LinkedIn',  'LinkedIn_13','user13@example.com','User 13 Name','https://example.com/profiles/user13.jpg','https://social.example.com/user13','talent'),
  ('Google',    'Google_14',   'user14@example.com','User 14 Name','https://example.com/profiles/user14.jpg','https://social.example.com/user14','talent_recruiter'),
  ('X',         'X_15',        'user15@example.com','User 15 Name','https://example.com/profiles/user15.jpg','https://social.example.com/user15','talent'),
  ('Instagram', 'Instagram_16','user16@example.com','User 16 Name','https://example.com/profiles/user16.jpg','https://social.example.com/user16','talent_recruiter'),
  ('LinkedIn',  'LinkedIn_17','user17@example.com','User 17 Name','https://example.com/profiles/user17.jpg','https://social.example.com/user17','talent'),
  ('Google',    'Google_18',   'user18@example.com','User 18 Name','https://example.com/profiles/user18.jpg','https://social.example.com/user18','talent_recruiter'),
  ('X',         'X_19',        'user19@example.com','User 19 Name','https://example.com/profiles/user19.jpg','https://social.example.com/user19','talent'),
  ('Instagram', 'Instagram_20','user20@example.com','User 20 Name','https://example.com/profiles/user20.jpg','https://social.example.com/user20','talent_recruiter'),
  ('LinkedIn',  'LinkedIn_21','user21@example.com','User 21 Name','https://example.com/profiles/user21.jpg','https://social.example.com/user21','talent'),
  ('Google',    'Google_22',   'user22@example.com','User 22 Name','https://example.com/profiles/user22.jpg','https://social.example.com/user22','talent_recruiter'),
  ('X',         'X_23',        'user23@example.com','User 23 Name','https://example.com/profiles/user23.jpg','https://social.example.com/user23','talent'),
  ('Instagram', 'Instagram_24','user24@example.com','User 24 Name','https://example.com/profiles/user24.jpg','https://social.example.com/user24','talent_recruiter'),
  ('LinkedIn',  'LinkedIn_25','user25@example.com','User 25 Name','https://example.com/profiles/user25.jpg','https://social.example.com/user25','talent'),
  ('Google',    'Google_26',   'user26@example.com','User 26 Name','https://example.com/profiles/user26.jpg','https://social.example.com/user26','talent_recruiter'),
  ('X',         'X_27',        'user27@example.com','User 27 Name','https://example.com/profiles/user27.jpg','https://social.example.com/user27','talent'),
  ('Instagram', 'Instagram_28','user28@example.com','User 28 Name','https://example.com/profiles/user28.jpg','https://social.example.com/user28','talent_recruiter'),
  ('LinkedIn',  'LinkedIn_29','user29@example.com','User 29 Name','https://example.com/profiles/user29.jpg','https://social.example.com/user29','talent'),
  ('Google',    'Google_30',   'user30@example.com','User 30 Name','https://example.com/profiles/user30.jpg','https://social.example.com/user30','talent_recruiter'),
  ('X',         'X_31',        'user31@example.com','User 31 Name','https://example.com/profiles/user31.jpg','https://social.example.com/user31','talent'),
  ('Instagram', 'Instagram_32','user32@example.com','User 32 Name','https://example.com/profiles/user32.jpg','https://social.example.com/user32','talent_recruiter'),
  ('LinkedIn',  'LinkedIn_33','user33@example.com','User 33 Name','https://example.com/profiles/user33.jpg','https://social.example.com/user33','talent'),
  ('Google',    'Google_34',   'user34@example.com','User 34 Name','https://example.com/profiles/user34.jpg','https://social.example.com/user34','talent_recruiter'),
  ('X',         'X_35',        'user35@example.com','User 35 Name','https://example.com/profiles/user35.jpg','https://social.example.com/user35','talent'),
  ('Instagram', 'Instagram_36','user36@example.com','User 36 Name','https://example.com/profiles/user36.jpg','https://social.example.com/user36','talent_recruiter'),
  ('LinkedIn',  'LinkedIn_37','user37@example.com','User 37 Name','https://example.com/profiles/user37.jpg','https://social.example.com/user37','talent'),
  ('Google',    'Google_38',   'user38@example.com','User 38 Name','https://example.com/profiles/user38.jpg','https://social.example.com/user38','talent_recruiter'),
  ('X',         'X_39',        'user39@example.com','User 39 Name','https://example.com/profiles/user39.jpg','https://social.example.com/user39','talent'),
  ('Instagram', 'Instagram_40','user40@example.com','User 40 Name','https://example.com/profiles/user40.jpg','https://social.example.com/user40','talent_recruiter'),
  ('LinkedIn',  'LinkedIn_41','user41@example.com','User 41 Name','https://example.com/profiles/user41.jpg','https://social.example.com/user41','talent'),
  ('Google',    'Google_42',   'user42@example.com','User 42 Name','https://example.com/profiles/user42.jpg','https://social.example.com/user42','talent_recruiter'),
  ('X',         'X_43',        'user43@example.com','User 43 Name','https://example.com/profiles/user43.jpg','https://social.example.com/user43','talent'),
  ('Instagram', 'Instagram_44','user44@example.com','User 44 Name','https://example.com/profiles/user44.jpg','https://social.example.com/user44','talent_recruiter'),
  ('LinkedIn',  'LinkedIn_45','user45@example.com','User 45 Name','https://example.com/profiles/user45.jpg','https://social.example.com/user45','talent'),
  ('Google',    'Google_46',   'user46@example.com','User 46 Name','https://example.com/profiles/user46.jpg','https://social.example.com/user46','talent_recruiter'),
  ('X',         'X_47',        'user47@example.com','User 47 Name','https://example.com/profiles/user47.jpg','https://social.example.com/user47','talent'),
  ('Instagram', 'Instagram_48','user48@example.com','User 48 Name','https://example.com/profiles/user48.jpg','https://social.example.com/user48','talent_recruiter'),
  ('LinkedIn',  'LinkedIn_49','user49@example.com','User 49 Name','https://example.com/profiles/user49.jpg','https://social.example.com/user49','talent'),
  ('Google',    'Google_50',   'user50@example.com','User 50 Name','https://example.com/profiles/user50.jpg','https://social.example.com/user50','talent_recruiter');
