CREATE TABLE IF NOT EXISTS public.job_titles (
  job_title_id SERIAL PRIMARY KEY,
  job_category VARCHAR(100) NOT NULL,
  job_title VARCHAR(255) NOT NULL,
  job_description TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
