name: Deploy Scoutjar-Server to Dev Instance

on:
  push:
    branches:
      - mvp0.1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Deploy to GCP instance
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.GCP_SERVER_IP }}
        username: ${{ secrets.GCP_DEPLOY_USER }}
        key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        script: |
          mkdir -p ~/projects/scoutjar
          cd ~/projects/scoutjar
          if [ ! -d "scoutjar-server" ]; then
            git clone https://github.com/jaypersanchez/scoutjar-server.git
          fi
          cd scoutjar-server
          git pull origin mvp0.1
          npm install
          pm2 start index.js --name scoutjar-server || pm2 restart scoutjar-server