name: Deploy Scoutjar-Server to Dev Instance

on:
  push:
    branches:
      - mvp0.1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to GCP instance
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.GCP_SERVER_IP }}
        username: ${{ secrets.GCP_DEPLOY_USER }}
        key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        script: |
          cd ~/scoutjar-server || (git clone git@github.com:jaypersanchez/scoutjar-server.git scoutjar-server && cd scoutjar-server)
          git pull origin mvp0.1
          npm install
          pm2 start index.js --name scoutjar-server || pm2 restart scoutjar-server
